[package]
name = "wgpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu-core = { path = "../wgpu-core" }
wgpu-hal = { path = "../wgpu-hal" }